config/routes.rb
Rails.application.routes.draw do
    get '/inscricoes' => 'subscribers#new', as: :new_subscriber
    post '/inscricoes/cadastrar' => 'subscribers#create', as: :create_subscriber
    get '/checkout' => 'payments#new', as: :new_payment
    post '/checkout/pagar' => 'payments#create', as: :create_payment
    root 'home#index'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    belongs_to :subscriber
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
    has_many :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    # TODO: use cookies instead of flash
    @subscriber_id = flash[:subscriber_id]
    if not @subscriber_id
      redirect_to new_subscriber_path
    else
      @payment = Payment.new
      render :new
    end
  end

  def create
    # TODO: implement bank slip payment
    Iugu.api_key = "52dc81f689986471896c07e68713fe58"
    @payment = Payment.new params.require(:payment).permit :token, :subscriber_id
    if @payment.save
      charge = Iugu::Charge.create({
        token: @payment.token,
        email: @payment.subscriber.email,
        items: [
          {
            description: "Inscrição Bootcamp Gama Academy",
            quantity: "1",
            price_cents: "3000"
          }
        ]
      })
      if charge and charge.success
        render "success"
      else
        render "fail"
      end
    else
      render :new
    end 
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @subscriber = Subscriber.new
    render :new
  end

  def create
    @subscriber = Subscriber.new params.require(:subscriber).permit :name, :email
    if @subscriber.save
      # TODO: use cookies instead of flash
      flash[:subscriber_id] = @subscriber.id
      redirect_to new_payment_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/home/index.html.erb
<h2>...informações sobre a Gama/bootcamp...</h2>
<%= link_to "Inscreva-se", new_subscriber_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IuguProto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield(:javascripts) %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/payments/fail.html.erb
Pagamento não aprovado :(

app/views/payments/new.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/formatter.js/0.1.5/formatter.min.js"></script>
  <script type="text/javascript" src="https://js.iugu.com/v2"></script>
<% end %>

<%= form_for @payment, { url: create_payment_path, html: { id: "payment-form" } } do |f| %>
  <div class="usable-creditcard-form">
    <div class="wrapper">
      <div class="input-group nmb_a">
        <div class="icon ccic-brand"></div>
        <input autocomplete="off" class="credit_card_number" data-iugu="number" placeholder="Número do Cartão" type="text" value="" />
      </div>
      <div class="input-group nmb_b">
        <div class="icon ccic-cvv"></div>
        <input autocomplete="off" class="credit_card_cvv" data-iugu="verification_value" placeholder="CVV" type="text" value="" />
      </div>
      <div class="input-group nmb_c">
        <div class="icon ccic-name"></div>
        <input class="credit_card_name" data-iugu="full_name" placeholder="Titular do Cartão" type="text" value="" />
      </div>
      <div class="input-group nmb_d">
        <div class="icon ccic-exp"></div>
        <input autocomplete="off" class="credit_card_expiration" data-iugu="expiration" placeholder="MM/AA" type="text" value="" />
      </div>
    </div>
    <div class="footer">
      <img src="http://storage.pupui.com.br/9CA0F40E971643D1B7C8DE46BBC18396/assets/cc-icons.e8f4c6b4db3cc0869fa93ad535acbfe7.png" alt="Visa, Master, Diners. Amex" border="0" />
      <a class="iugu-btn" href="http://iugu.com" tabindex="-1"><img src="http://storage.pupui.com.br/9CA0F40E971643D1B7C8DE46BBC18396/assets/payments-by-iugu.1df7caaf6958f1b5774579fa807b5e7f.png" alt="Pagamentos por Iugu" border="0" /></a>
    </div>
  </div>
  <%= f.hidden_field :token, id: "token" %>
  <%= f.hidden_field :subscriber_id, value: @subscriber_id %>
  <%= f.submit "Confirmar", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
Iugu.setAccountID("8c7d347d-4108-449d-9a63-a2f0985d651d");
Iugu.setTestMode(true); // TODO: disable for production

jQuery(function($) {
  $('#payment-form').submit(function(evt) {
    var form = $(this);
    var tokenResponseHandler = function(data) {

      if (data.errors) {
        // console.log(data.errors);
        alert("Erro salvando cartão: " + JSON.stringify(data.errors));
      } else {
        $("#token").val( data.id );
        form.get(0).submit();
      }

      // Seu código para continuar a submissão
      // Ex: form.submit();
    }

    Iugu.createPaymentToken(this, tokenResponseHandler);
    return false;
  });
});
</script>

app/views/payments/success.html.erb
Pagamento realizado com sucesso!

app/views/subscribers/new.html.erb
<% if @subscriber.errors.size > 0 %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @subscriber.errors.each_with_index do |message| %>
        <li><%= message[1] %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @subscriber, url: create_subscriber_path do |f| %>
  <div class="form-group">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, "E-mail" %>
    <%= f.email_field :email, class: "form-control"%>
  </div>
  <%= f.submit "Inscrever", class: "btn btn-primary" %>
<% end %>